### ISSUE TITLE
Python 3.12 support wonky

### ISSUE THREAD

**Issue by biemster** [Dadoum/pyprovision#13]
There are two commits that mention python 3.12 support, and the `pyd` fork used here has a similar commit, but when I try to pip install this on a py3.12 only machine the packager still searches for libpython3.11.

I am aware of pyenv and the like, but since there are attempts to support pure 3.12 is it possible to get this working on such machines? This would reduce the hassle considerably when installing on machines on a rolling release.

**Comment by biemster** [comment]
Thanks! But maybe not fully done yet? There is still this:
https://github.com/Dadoum/pyprovision/blob/1790e0cd55f8e56d5fac27a2e97636c421fa8da6/setup.py#L37

And now I get the following error:
```bash
['pyprovision', '.gitignore', 'setup.py', 'example.py', '.git', 'LICENSE', 'README.md']
      dub build -c python312 -b release
          Fetching pyd 0.14.4 (getting selected version)
           Warning The sub configuration directive "pyd" -> [python312] references a configuration that does not exist.
           Warning The sub configuration directive "pyd" -> [python313] references a configuration that does not exist.
      Error Could not resolve configuration for package pyd

```
(but the latter might be due to me not understanding how to update dependencies, I just did a `git pull` and `pip install .`)

**Comment by Dadoum** [comment]
Try to use `dub update` in the pyprovision folder

**Comment by biemster** [comment]
`dub upgrade` worked! (`update` doesn't exist). Still need the `minor = minor if minor <= 13 else 13` change, but I got it successfully installed now, thanks!

**Comment by Dadoum** [comment]
I committed the changes from dub upgrade (I should delete the dub selection file altogether but I can't do it from the GitHub web UI so eh good enough), and fixed the setup.py as you said.
